apiVersion: v1
kind: Service
metadata:
  name: luffy-app
  labels:
    app: luffy-app
spec:
  type: NodePort
  ports:
  - port: 80
    targetPort: 80
    nodePort: 30007
  selector:
    app: luffy-app
